version: ~> 1.0
language:
  - cpp
  - php
branches:
  only:
    - master
os:
  - linux
  - osx
dist: bionic
osx_image: xcode14.2
addons:
  snaps:
    - name: cmake
      confinement: classic
      channel: latest/stable
  apt:
    update: false
    packages:
      - ninja-build      
  homebrew:
    update: true
    packages:
      - cmake
      - ninja
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
arch:
  - amd64
  - arm64
  - aarch64
  - armhf
before_script:
  - ./configure.sh cmake-info
script:
  - ./configure.sh build
compiler:
  - g++
