version: ~> 1.0
language:
  - cpp
  - php
branches:
  only:
    - master
os:
  - linux
  - osx
dist: bionic
osx_image: xcode14.3
install:
  - cmake
  - ninja
arch:
  - amd64
  - arm64
compiler:
  - g++
jobs:
  include:
    - stage: configure
      - script: ./autoconf.sh configure
    - stage: build
      - script: ./autoconf.sh build
    - stage: test
      - script: ./autoconf.sh test
