version: ~> 1.0
language:
  - cpp
  - php
branches:
  only:
    - master
os:
  - linux
  - osx
dist: bionic
osx_image: xcode14.3
install:
  - cmake
  - ninja
arch:
  - amd64
  - arm64
compiler:
  - g++
stages:
  - name: configure
    - script: ./autoconf.sh configure
  - name: build
    - script: ./autoconf.sh build
  - name: test
    - script: ./autoconf.sh test
