version: ~> 1.0
language:
  - cpp
  - php
branches:
  only:
  - master
os:
  - linux
  - osx
dist: bionic
osx_image: xcode14.3
install:
  - cmake 3.26.3
  - ninja
arch:
  - amd64
  - arm64
compiler:
  - g++
stages:
  - name: configure
