language:
  - cpp
  - php
branches:
  only:
    - master
os:
  - linux
  - osx
dist: bionic
osx_image: xcode14.3
addons:
  homebrew:
    packages:
      - cmake
      - ninja
      update: true
  apt:
    packages:
      - cmake
      - ninja-build
arch:
  - amd64
  - arm64
compiler:
  - g++
jobs:
  include:
    - script: "./autoconf.sh configure"
    - script: ./autoconf.sh build
    - script: ./autoconf.sh test
