version: ~> 1.0
language:
  - cpp
  - php
branches:
  only:
    - master
dist: bionic
addons:
  snaps:
    - name: cmake
      confinement: classic
      channel: latest/stable
  apt:
    update: true
    packages:
      - ninja-build
  homebrew:
    update: true
    packages:
      - cmake
      - ninja
jobs:
  include:
    - os: linux
      arch: amd64
      compiler: g++
    - os: linux
      arch: amd64
      compiler: clang++
    - os: linux
      arch: arm64
      compiler: g++
    - os: linux
      arch: arm64
      compiler: clang++
    - os: osx
      osx_image: xcode14.2
      compiler: clang++
before_script:
  - ./configure.sh cmake-info
script:
  - ./configure.sh build
