version: ~> 1.0
language:
  - cpp
  - php
branches:
  only:
  - master
os:
  - linux
  - osx
dist: bionic
osx_image: xcode14.3
install:
  - cmake
  - ninja
arch:
  - amd64
  - arm64
compiler:
  - g++
stages:
  - name: configure
    - script : cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/install --check-system-vars -S . -B build -G Ninja
  - name: build
    - script : cmake --build build --clean-first --verbose --target magic-eightball
  - name: test
    - script : build/magic-eightball -q "Will this build work?"
