version: ~> 1.0
language:
  - cpp
  - php
branches:
  only:
    - master
os:
  - linux
  - osx
dist: bionic
addons:
  snaps:
    - name: cmake
      confinement: classic
      channel: latest/stable
  apt:
    update: true
    packages:
      - ninja-build
osx_image: xcode14.3
addons:
  homebrew:
    update: true
    packages:
      - cmake
      - ninja
arch:
  - amd64
  - arm64
  - aarch64
  - armhf
script:
  - cmake --preset release
  - cmake --build --preset release
  - build/magic-eightball -q "Do you think this will work?"
compiler:
  - g++
