language:
  - cpp
  - php
branches:
  only:
    - master
os:
  - linux
  - osx
dist: bionic
osx_image: xcode14.3
install:
  - cmake
  - ninja
arch:
  - amd64
  - arm64
compiler:
  - g++
jobs:
  include:
    - script: "./autoconf.sh configure"
    - script: ./autoconf.sh build
    - script: ./autoconf.sh test
